import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_exam_result_pdf(exam_id, db_instance, output_dir="output"):
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Fetch exam details
    db_instance.cursor.execute("SELECT exam_name, class_name, total_marks, exam_date FROM Exams WHERE exam_id = ?", (exam_id,))
    exam_info = db_instance.cursor.fetchone()
    if not exam_info:
        return None
    exam_name, class_name, total_marks, exam_date = exam_info

    # Fetch marks and stats
    highest = db_instance.get_highest_marks_for_exam(exam_id)
    average = db_instance.get_average_marks_for_exam(exam_id)
    students_marks = db_instance.get_marks_by_exam(exam_id)
    
    # Sort students by obtained marks descending
    students_marks.sort(key=lambda x: x[2] if x[2] is not None else -1, reverse=True)

    # Generate filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Result_{class_name.replace(' ', '')}_{exam_name.replace(' ', '_')}_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    # Create document
    doc = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=50, bottomMargin=50)
    story = []
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    subtitle_style = styles['Heading2']
    subtitle_style.alignment = 1
    
    normal_style = styles['Normal']

    # Header
    story.append(Paragraph("Local Coaching Center", title_style))
    story.append(Paragraph(f"Result Sheet: {exam_name}", subtitle_style))
    story.append(Spacer(1, 12))
    
    # Setup Information Table
    info_data = [
        ["Class:", class_name, "Date:", exam_date],
        ["Total Marks:", str(total_marks), "Highest Marks:", str(highest)],
        ["Average Marks:", f"{average:.2f}", "", ""]
    ]
    
    info_table = Table(info_data, colWidths=[100, 150, 100, 150])
    info_table_style = TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.darkblue),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8)
    ])
    info_table.setStyle(info_table_style)
    story.append(info_table)
    story.append(Spacer(1, 20))

    # Results Table
    table_data = [["Rank", "Student ID", "Student Name", "Obtained Marks", "Percentage"]]
    
    for rank, (std_id, name, marks) in enumerate(students_marks, start=1):
        if marks is None:
            marks_str = "Absent"
            percentage_str = "N/A"
        else:
            marks_str = str(marks)
            percentage = (marks / total_marks) * 100
            percentage_str = f"{percentage:.2f}%"
        
        table_data.append([str(rank), std_id, name, marks_str, percentage_str])

    result_table = Table(table_data, colWidths=[50, 100, 200, 100, 80])
    result_table_style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.ivory),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ])
    result_table.setStyle(result_table_style)
    story.append(result_table)

    # Footer
    story.append(Spacer(1, 40))
    story.append(Paragraph("Generated by Admin", normal_style))
    
    # Build
    doc.build(story)
    
    return os.path.abspath(filepath)
