import os
from datetime import datetime
from fpdf import FPDF

class PDF(FPDF):
    def __init__(self, exam_name):
        super().__init__()
        self.exam_name = exam_name

    def header(self):
        # Arial bold 15
        self.set_font("Helvetica", "B", 15)
        # Title
        self.cell(0, 10, "Local Coaching Center", align="C")
        self.ln(8)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 10, f"Result Sheet: {self.exam_name}", align="C")
        # Line break
        self.ln(20)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, "Generated by Admin", align="C")


def generate_exam_result_pdf(exam_id, db_instance, output_dir="output"):
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Fetch exam details
    db_instance.cursor.execute("SELECT exam_name, class_name, total_marks, exam_date FROM Exams WHERE exam_id = ?", (exam_id,))
    exam_info = db_instance.cursor.fetchone()
    if not exam_info:
        return None
    exam_name, class_name, total_marks, exam_date = exam_info

    # Fetch marks and stats
    highest = db_instance.get_highest_marks_for_exam(exam_id)
    average = db_instance.get_average_marks_for_exam(exam_id)
    students_marks = db_instance.get_marks_by_exam(exam_id)
    
    # Sort students by obtained marks descending
    students_marks.sort(key=lambda x: x[2] if x[2] is not None else -1, reverse=True)

    # Generate filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Result_{class_name.replace(' ', '')}_{exam_name.replace(' ', '_')}_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf = PDF(exam_name)
    pdf.add_page()
    
    # Setup Information
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 0, 139) # Dark blue
    
    # Line 1
    pdf.cell(30, 8, "Class:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 8, str(class_name))
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(30, 8, "Date:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 8, str(exam_date))
    pdf.ln(8)
    
    # Line 2
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(30, 8, "Total Marks:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 8, str(total_marks))
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(30, 8, "Highest Marks:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 8, str(highest))
    pdf.ln(8)

    # Line 3
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(30, 8, "Average Marks:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(60, 8, f"{average:.2f}")
    pdf.ln(16)
    
    pdf.set_text_color(0, 0, 0) # Black

    # Results Table Header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(128, 128, 128) # Grey
    pdf.set_text_color(245, 245, 245) # Whitesmoke
    
    col_widths = [20, 30, 70, 40, 30]
    headers = ["Rank", "Student ID", "Student Name", "Obtained Marks", "Percentage"]
    
    for width, header in zip(col_widths, headers):
        pdf.cell(width, 10, header, border=1, align="C", fill=True)
    pdf.ln(10)
    
    # Table Content
    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(255, 255, 240) # Ivory
    pdf.set_text_color(0, 0, 0)
    
    fill = False
    for rank, (std_id, name, marks) in enumerate(students_marks, start=1):
        if marks is None:
            marks_str = "Absent"
            percentage_str = "N/A"
        else:
            marks_str = str(marks)
            percentage = (marks / total_marks) * 100
            percentage_str = f"{percentage:.2f}%"
            
        pdf.cell(col_widths[0], 10, str(rank), border=1, align="C", fill=fill)
        pdf.cell(col_widths[1], 10, str(std_id), border=1, align="C", fill=fill)
        pdf.cell(col_widths[2], 10, str(name), border=1, align="L", fill=fill)
        pdf.cell(col_widths[3], 10, marks_str, border=1, align="C", fill=fill)
        pdf.cell(col_widths[4], 10, percentage_str, border=1, align="C", fill=fill)
        pdf.ln(10)
        
        fill = not fill # Alternate background color
        
    pdf.output(filepath)
    return os.path.abspath(filepath)
